name: flutter_qiniu_qetag
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/bykenx/flutter_qiniu_qetag

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  crypto: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/test_file.txt
